
modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="MIT License"
[[mods]]
modId="petrochem"
version="${file.jarVersion}"
displayName="Gearbox"
credits="#devchat folks"
authors="Redz aka terentre4e25caracteres" #optional
description='''
The definitive petrol experience
'''
[[dependencies.petrochem]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.petrochem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.petrochem]]
    modId="create"
    mandatory=true
    versionRange="[0.6.4,)"
    ordering="NONE"
    side="BOTH"
